### ISSUE TITLE
Presets for Extracting Audio

### ISSUE THREAD

**Issue by turtlepurple** [Ilias95/FF-Multi-Converter#17]
I'm suggesting two new presets. It seems plain, but is whats most needed to get music out of video-downloads.

Greets

CopyExtractAudioAAC
Extract (copy) audio AAC (mp4-video->aac-audio)
-acodec copy
aac

CopyExtractAudioMP3
Extract (copy) audio Mp3 (FLV-video->mp3-audio)
-acodec copy
mp3

**Comment by turtlepurple** [comment]
Hey there,
Just had a little jay, when I realised they're alrdy included.

A fix though:
For CopyExtractAudioAAC
the output-extension should be .m4a
.aac might seem logical but i'm not sure if it's even ment to be a file-format or just a codec.
Anyway it produces problems: Audacious plays the file but says "lseek failed"
Puddletag wont take the file.

On the other side m4a is perfectly correct because its just another "audio-only" extension for mp4.
Never had problems with any audio-player and puddletag works with it, too.

Greets

**Comment by Ilias95** [comment]
done: 8d2adcb4e845ead6beddf7563fb814f11ce2465a
