### ISSUE TITLE
Each conversion takes longer than the last

### ISSUE THREAD

**Issue by pooky2483** [Ilias95/FF-Multi-Converter#34]
When doing a batch convert, the time it takes to do the next one is longer than the last.
Take the batch I left it with last night. Each file was 847.5, 810.8, 831.4, 795.1Mb and the time it took to convert each file was 1h:34m, 2h:07m, 3h:33m, 4h:59m. This is not a one-off as it happens all the time until it seem to just 'hang', taking forever to convert the next file.

I have updated to the latest version too, 1.70
AMD Phenom(tm) II X4 965 Processor
8Gb Ram
KDELibs 4.12.4
QT 4.8.6
Kernel 3.13.0-48
OS Kubuntu 14.10 64bit
ffmpeg 7:1.2.6-1~trusty1
imagemagick 8:6.7.7.10~6ubuntu3
unoconv 0.6-6

**Comment by Ilias95** [comment]
Hello, 

First of all, what exactly do you mean by batch convert? 
Choosing multiple files and clicking convert (and so using the same parameters for each conversion) or choose a file, click convert, then choosing another file, click convert, etc, so all conversions occur simultaneously?

**Comment by pooky2483** [comment]
I only know of ONE way to perform a 'batch convert' and that is the first way you describe it. The second is NOT 'batch convert'. Queueing up a selection of files and then selecting 'convert'.

I am currently batch converting '.avi' files and they are taking, on average 20 minutes. The files I am having problems with are '.mkv'. I am converting to '.mkv' and have just wondered if it is that which is the problem!

**Comment by Ilias95** [comment]
Currently when you convert files this way, the conversions will occur serially and so that's why "each file takes longer than the last". No conversion will start until the previous is done.

It's a good thought though to have batch conversions run simultaneously and I'm probably going to implement it.

For now, the only way to make parallel conversions is the second one I've described above. You just clear the files list, choose another file, hit convert and a second window will appear showing the progress of the second conversion.

If you although mean that the actual conversion time of each file when converting serially significantly differs, I can't reproduce it even when converting to mkv.

**Comment by pooky2483** [comment]
Currently when you convert files this way, the conversions will occur serially and so that's why "each file takes longer than the last". No conversion will start until the previous is done.

I don't think you quite understood what I meant. 
The time it takes for the first file to be converted could be 10 minutes and then the next file could take 20 minutes and then the third, 30 minutes. I am not taking the start time from when I clicked on 'convert' but the timestamp of the last file converted.
------------
It's a good thought though to have batch conversions run simultaneously and I'm probably going to implement it.

Won't that make it take even longer and use too much processor
------------
For now, the only way to make parallel conversions is the second one I've described above. You just clear the files list, choose another file, hit convert and a second window will appear showing the progress of the second conversion.

You've lost me there.
------------
If you although mean that the actual conversion time of each file when converting serially significantly differs, I can't reproduce it even when converting to mkv. 

I do

**Comment by pooky2483** [comment]
Regarding the first paragraph, this is what I mean about the times;
![example of times](https://cloud.githubusercontent.com/assets/3163682/7034221/f87354b8-dd77-11e4-9ced-5307522cffd2.jpg)

**Comment by Ilias95** [comment]
Hmm, I managed to reproduce it using the libx264 vcodec. When converting to flv or avi, times are approximately the same. Not sure if it's an ffmpeg or ffmulticonverter issue. 

What are the exact parameters that you pass to ffmpeg?

**Comment by pooky2483** [comment]
The ones that are there when I select the conversion;
Parameters : -ab 320k -ar 48000 -ac 2 (No preset)
Convert to .MKV
Video & Audio codec are set to default

**Comment by pooky2483** [comment]
Just had another look at it and I realised that it HAS a 'preset', it's the current parameters. I just didn’t select one from the preset menu and used the 'default'.

**Comment by Ilias95** [comment]
It's definitely an ffmpeg issue.
I can reproduce it without using ffmulticonverter at all, by converting files using the command line. When converting to mkv my CPU usage is permanently 95-100%. When I'm trying to convert larger files, the whole system hangs after a few minutes.
