### ISSUE TITLE
ff multi converter hangs

### ISSUE THREAD

**Issue by Tidefan35967** [Ilias95/FF-Multi-Converter#35]
After setting up video parameters. I click the convert button and it and the conversion window pops up. It will stay at zero % for as long as I let it. I click the cancel button and nothing happens. Try to close the conversion window and nothing. I then have to close out the entire program. No error codes. Am I doing something wrong?

**Comment by Ilias95** [comment]
You should provide some more information, such as your distribution, and the package version.

Also, independently of the conversion window, does the app produces output files?
Any text output, when launching from a terminal?

**Comment by Tidefan35967** [comment]
I'll admit, I'm a noob to linux. I had ubuntu ver. 1.6. I have uninstalled and plan on trying 1.7. Is there anything I should know when running it on mint?

**Comment by Ilias95** [comment]
For Linux Mint, I would recommend installing the latest version from source as described here: https://github.com/Ilias95/FF-Multi-Converter/wiki/Installing-from-source
It's very simple, and a nice uninstall script is also included.

If the problem remains, please launch the application from a terminal and see if it produces any output on it.

**Comment by Tidefan35967** [comment]
Trying to install 1.7 keep getting "error: could not create '/usr/local/lib/python3.4/dist-packages/ffmulticonverter': Permission denied" Any help?

**Comment by Ilias95** [comment]
You should run the installation command as root, therefore run it with a sudo prefix.

Also, before installing it this way, be sure that you completely removed the previous installation.

**Comment by Tidefan35967** [comment]
Works perfectly! Thanks for the patience and awesome support!!

**Comment by Ilias95** [comment]
I'm glad it worked out. :)
