### ISSUE TITLE
Unable to convert <some> formats

### ISSUE THREAD

**Issue by pooky2483** [Ilias95/FF-Multi-Converter#43]
I am trying to convert 'MP4' and I can convert <some> formats but it fails to convert others.
Here is the metadata on one of the videos it is failing to convert. I have others and will post here when I find one that fails.
METADATA
General
Complete name                            : /media/pooky2483/EXT-02/Series/BBC.The.Hairy.Bikers.Asian.Adventure.1of6.Hong.Kong.720p.HDTV.x264.AAC.MVGroup.org.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 916 MiB
Duration                                 : 58mn 44s
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 180 Kbps
Encoded date                             : UTC 2014-03-21 11:00:35
Tagged date                              : UTC 2014-03-21 11:00:35
Writing application                      : My MP4Box GUI 0.6.0.0 <http://my-mp4box-gui.zymichost.com>

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings, CABAC                   : No
Format settings, ReFrames                : 1 frame
Format settings, GOP                     : M=1, N=12
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 58mn 44s
Bit rate                                 : 2 017 Kbps
Maximum bit rate                         : 13.4 Mbps
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.088
Stream size                              : 848 MiB (93%)
Title                                    : BBC.The.Hairy.Bikers.Asian.Adventure.1of6.Hong.Kong.720p.HDTV.x264.AAC.MVGroup.org.mp4
Encoded date                             : UTC 2014-03-21 00:56:38
Tagged date                              : UTC 2014-03-21 11:01:38

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 58mn 44s
Bit rate mode                            : Variable
Bit rate                                 : 160 Kbps
Maximum bit rate                         : 210 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 67.2 MiB (7%)
Title                                    : BBC.The.Hairy.Bikers.Asian.Adventure.1of6.Hong.Kong.720p.HDTV.x264.AAC.MVGroup.org.mp4
Language                                 : English
Encoded date                             : UTC 2014-03-21 11:01:35
Tagged date                              : UTC 2014-03-21 11:01:38

Text
ID                                       : 3
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 58mn 34s
Bit rate mode                            : Variable
Bit rate                                 : 107 bps
Stream size                              : 45.9 KiB (0%)
Title                                    : BBC.The.Hairy.Bikers.Asian.Adventure.1of6.Hong.Kong.720p.HDTV.x264.AAC.MVGroup.org.srt
Encoded date                             : UTC 2014-03-21 11:01:38
Tagged date                              : UTC 2014-03-21 11:01:38

I hope this is enough info, I am also using the newest version of FFMultiConverter - 1.7.2 (just installed)

**Comment by Ilias95** [comment]
For this kind of troubleshooting we need the actual file and/or the "Details" appearing on the conversion window when you get the error.

**Comment by pooky2483** [comment]
How can I get you the file, what's the best way to send it?

**Comment by Ilias95** [comment]
You can upload it to any hosting service you like and post the link here (unfortunately github doesn't support attaching such file types yet). Please post the "Details" for this specific conversion as well.

**Comment by pooky2483** [comment]
Here is a link to a file I tried to convert tonight but it failed.
http://1drv.ms/1MbHoS6

**Comment by Ilias95** [comment]
As I said, I need the Details for this conversion too. :)
Just try to convert the file with the options you want, and when it fails copy everything from the Details field and paste it here.

**Comment by pooky2483** [comment]
It simply failed to convert, no explanation was given.

**Comment by pooky2483** [comment]
Here' s the data for the failed convert of the video.
avconv -y -i "/media/EXT-02/Series/Egypt/Paranormal Egypt/E01 - Ramesses.mp4"  "/media/EXT-02/Series/Egypt/Paranormal Egypt/E01 - Ramesses.mkv"
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/media/EXT-02/Series/Egypt/Paranormal Egypt/E01 - Ramesses.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2036-02-06 06:28:16
    encoder         : HandBrake 0.10.2 2015060900
  Duration: 00:45:04.74, start: 0.000000, bitrate: 1961 kb/s
    Chapter #0.0: start 0.000000, end 530.000000
    Metadata:
      title           : Chapter 1
    Chapter #0.1: start 530.000000, end 903.820000
    Metadata:
      title           : Chapter 2
    Chapter #0.2: start 903.820000, end 1314.100000
    Metadata:
      title           : Chapter 3
    Chapter #0.3: start 1314.100000, end 1674.600000
    Metadata:
      title           : Chapter 4
    Chapter #0.4: start 1674.600000, end 2166.120000
    Metadata:
      title           : Chapter 5
    Chapter #0.5: start 2166.120000, end 2704.164000
    Metadata:
      title           : Chapter 6
    Stream #0.0(und): Video: h264 (Main), yuv420p, 720x570 [PAR 64:45 DAR 512:285], 1796 kb/s, 25 fps, 25 tbr, 90k tbn, 180k tbc
    Metadata:
      creation_time   : 2036-02-06 06:28:16
    Stream #0.1(eng): Audio: aac, 48000 Hz, stereo, fltp, 160 kb/s
    Metadata:
      creation_time   : 2036-02-06 06:28:16
    Stream #0.2(eng): Subtitle: text / 0x74786574
    Metadata:
      creation_time   : 2036-02-06 06:28:16
[libx264 @ 0x1eb6b20] using SAR=64/45
[libx264 @ 0x1eb6b20] MB rate (145800000) > level limit (2073600)
[libx264 @ 0x1eb6b20] using cpu capabilities: MMX2 SSE2Fast LZCNT
[libx264 @ 0x1eb6b20] profile High, level 5.2
[libx264 @ 0x1eb6b20] 264 - core 142 r2389 956c8d8 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.25 aq=1:1.00
Output #0, matroska, to '/media/EXT-02/Series/Egypt/Paranormal Egypt/E01 - Ramesses.mkv':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2036-02-06 06:28:16
    encoder         : HandBrake 0.10.2 2015060900
    Chapter #0.0: start 0.000000, end 530.000000
    Metadata:
      title           : Chapter 1
    Chapter #0.1: start 530.000000, end 903.820000
    Metadata:
      title           : Chapter 2
    Chapter #0.2: start 903.820000, end 1314.100000
    Metadata:
      title           : Chapter 3
    Chapter #0.3: start 1314.100000, end 1674.600000
    Metadata:
      title           : Chapter 4
    Chapter #0.4: start 1674.600000, end 2166.120000
    Metadata:
      title           : Chapter 5
    Chapter #0.5: start 2166.120000, end 2704.164000
    Metadata:
      title           : Chapter 6
    Stream #0.0(und): Video: libx264, yuv420p, 720x570 [PAR 64:45 DAR 512:285], q=-1--1, 90k tbn, 90k tbc
    Metadata:
      creation_time   : 2036-02-06 06:28:16
    Stream #0.1(eng): Audio: libvorbis, 48000 Hz, stereo, fltp
    Metadata:
      creation_time   : 2036-02-06 06:28:16
    Stream #0.2(eng): Subtitle: ass, 200 kb/s
    Metadata:
      creation_time   : 2036-02-06 06:28:16
Stream mapping:
  Stream #0:0 -> #0:0 (h264 -> libx264)
  Stream #0:1 -> #0:1 (aac -> libvorbis)
  Stream #0:2 -> #0:2 (? -> ass)
Error while opening encoder for output stream #0:2 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by pooky2483** [comment]
I've also just discovered I can't convert AVI to MP4 but it will convert the AVI to MKV.
Do you require the AVI file?

**Comment by Ilias95** [comment]
From the log you posted, it seems that you actually use avconv rather than ffmpeg. Could you please, install ffmpeg in your distribution (if you use Ubuntu or so, you may unfortunately need an external ppa), and see if the error remains?

The thing is that newer versions of ffmpeg and avconv are far from compatible. Maybe I'll drop avconv "support" in the next ffmulti version.

**Comment by pooky2483** [comment]
Installed ffmpeg, it was quite a task to find a copy that compiled and installed OK and to find a working PPA.
I'll get back to you with the results on the ones that didn’t convert earlier ASAP.

**Comment by pooky2483** [comment]
Hi Ilias95,
Hope you had a good Christmas.
I've got an AVI that wouldn’t convert...
Here's the link (http://1drv.ms/1P7U6aG) to the file and the output from the conversion is attached below...

(For some reason the site is having a wobbly and not letting me upload the text file, so I'm having to paste it instead. It's saying it can't process the file!)

ffmpeg -y -i "/media/EXT-06/TV_Series/E/Earth_-_Final_Conflict_(05)/Season_01_-_EFC_(22)/EFC 0101 - Decision.avi"  "/media/EXT-06/TV_Series/E/Earth_-_Final_Conflict_(05)/Season_01_-_EFC_(22)/EFC 0101 - Decision.mkv"
ffmpeg version 2.4.3-1ubuntu1~trusty6 Copyright (c) 2000-2014 the FFmpeg developers
  built on Nov 22 2014 17:07:19 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --prefix=/usr --extra-version='1ubuntu1~trusty6' --build-suffix=-ffmpeg --toolchain=hardened --extra-cflags= --extra-cxxflags= --libdir=/usr/lib/x86_64-linux-gnu --shlibdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --enable-shared --disable-stripping --enable-avresample --enable-avisynth --enable-fontconfig --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-opengl --enable-x11grab --enable-libxvid --enable-libx265 --enable-libdc1394 --enable-libiec61883 --enable-libzvbi --enable-libzmq --enable-frei0r --enable-libx264 --enable-libsoxr --enable-openal --enable-libopencv
  libavutil      54.  7.100 / 54.  7.100
  libavcodec     56.  1.100 / 56.  1.100
  libavformat    56.  4.101 / 56.  4.101
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  1.100 /  5.  1.100
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  0.100 / 53.  0.100
Input #0, avi, from '/media/EXT-06/TV_Series/E/Earth_-_Final_Conflict_(05)/Season_01_-_EFC_(22)/EFC 0101 - Decision.avi':
  Metadata:
    encoder         : VirtualDubMod 1.5.10.2 (build 2540/release)
  Duration: 00:41:38.24, start: 0.000000, bitrate: 1175 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 512x384 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 25 tbn, 25 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 129 kb/s
[libx264 @ 0x12117a0] using SAR=1/1
[libx264 @ 0x12117a0] using cpu capabilities: MMX2 SSE2Fast LZCNT
[libx264 @ 0x12117a0] profile High, level 2.1
[libx264 @ 0x12117a0] 264 - core 142 r2389 956c8d8 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, matroska, to '/media/EXT-06/TV_Series/E/Earth_-_Final_Conflict_(05)/Season_01_-_EFC_(22)/EFC 0101 - Decision.mkv':
  Metadata:
    encoder         : Lavf56.4.101
    Stream #0:0: Video: h264 (libx264) (H264 / 0x34363248), yuv420p, 512x384 [SAR 1:1 DAR 4:3], q=-1--1, 25 fps, 1k tbn, 25 tbc
    Metadata:
      encoder         : Lavc56.1.100 libx264
    Stream #0:1: Audio: vorbis (libvorbis) (oV[0][0] / 0x566F), 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc56.1.100 libvorbis
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (mp3 (native) -> vorbis (libvorbis))
Press [q] to stop, [?] for help
[mpeg4 @ 0x17c44c0] Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using a tool like VirtualDub or avidemux to fix it.
frame=   91 fps=0.0 q=28.0 size=      88kB time=00:00:04.26 bitrate= 169.1kbits/s    
[mpeg4 @ 0x17cac00] ac-tex damaged at 18 20
[mpeg4 @ 0x17cac00] Error at MB: 678
[mpeg4 @ 0x17cac00] marker does not match f_code
    Last message repeated 4984 times
[mpeg4 @ 0x17cac00] concealing 159 DC, 159 AC, 159 MV errors in P frame
frame=  141 fps= 21 q=28.0 size=     206kB time=00:00:06.16 bitrate= 273.9kbits/s    
frame=  144 fps= 20 q=-1.0 Lsize=     340kB time=00:00:06.23 bitrate= 446.1kbits/s    
video:259kB audio:73kB subtitle:0kB other streams:0kB global headers:4kB muxing overhead: 2.371250%
[libx264 @ 0x12117a0] frame I:2     Avg QP:12.46  size:   914
[libx264 @ 0x12117a0] frame P:52    Avg QP:22.93  size:  4042
[libx264 @ 0x12117a0] frame B:90    Avg QP:24.37  size:   578
[libx264 @ 0x12117a0] consecutive B-frames:  3.5% 20.8% 56.2% 19.4%
[libx264 @ 0x12117a0] mb I  I16..4: 73.4% 26.6%  0.0%
[libx264 @ 0x12117a0] mb P  I16..4:  3.1% 12.8%  1.2%  P16..4: 39.2% 14.9%  8.5%  0.0%  0.0%    skip:20.3%
[libx264 @ 0x12117a0] mb B  I16..4:  0.7%  1.7%  0.0%  B16..8: 37.1%  1.4%  0.1%  direct: 0.6%  skip:58.4%  L0:44.0% L1:51.0% BI: 5.0%
[libx264 @ 0x12117a0] 8x8 transform intra:67.0% inter:80.9%
[libx264 @ 0x12117a0] coded y,uvDC,uvAC intra: 33.6% 29.3% 3.7% inter: 12.0% 10.4% 0.1%
[libx264 @ 0x12117a0] i16 v,h,dc,p: 55% 22% 16%  6%
[libx264 @ 0x12117a0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 20% 40%  1%  1%  1%  1%  1%  2%
[libx264 @ 0x12117a0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 37% 29% 12%  2%  4%  4%  4%  4%  4%
[libx264 @ 0x12117a0] i8c dc,h,v,p: 67% 13% 19%  1%
[libx264 @ 0x12117a0] Weighted P-Frames: Y:23.1% UV:15.4%
[libx264 @ 0x12117a0] ref P L0: 61.5% 26.9%  9.0%  2.7%  0.0%
[libx264 @ 0x12117a0] ref B L0: 91.0%  8.8%  0.2%
[libx264 @ 0x12117a0] ref B L1: 94.2%  5.8%
[libx264 @ 0x12117a0] kb/s:366.69

**Comment by pooky2483** [comment]
OOPS!
Sorry, clicked on the wrong one, I think the 'Close & Comment' should be in RED to be able to identify them.

**Comment by Ilias95** [comment]
Hello and sorry for my late reply.

First of all, the file you listed is corrupted in some way. Here's what VLC displays when I try to open it:
![screenshot from 2016-02-13 20-28-06](https://cloud.githubusercontent.com/assets/982045/13029277/6b574a44-d290-11e5-9306-54668da9013f.png)

It's size is quite big too for debugging purposes.

Anyway, apart from these things, the "problem" is that you don't really choose any parameters for the conversion such as proper video and audio codecs for this kind of conversion. Try to experiment with your options for a while until you find suitable codecs for each type of file.

Cheers.
