### ISSUE TITLE
Porting to Qt5

### ISSUE THREAD

**Issue by proninyaroslav** [Ilias95/FF-Multi-Converter#45]
Hello. Qt4 is already EOL, so it is logical to port the application to Qt5. You are planning to in the near future to do this? I could help you with this.

**Comment by Ilias95** [comment]
Hello there,

Actually, I was thinking to perform a complete re-write of the whole application. At the moment, I believe that the code is kinda sloppy in many places and it could be written in a more structured and clean way. When I'll do this I definitely intend to port it to Qt5, and also change the GUI, add unit tests and maybe other stuff.

Unfortunately though, I don't know when will I have sufficient time for doing that and it may be even delayed until the summer period.

At some point I will start a separate branch for the new qt5 version. 
Any help would be welcome of course.

Best,
Ilias

**Comment by proninyaroslav** [comment]
Ok, I will wait.

**Comment by Ilias95** [comment]
Hi again,

I just created the 'pyqt5-port' branch and started by fixing the imports. Next step is to fix the inconsistencies with the new QFileDialog (http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html). Feel free to report any bugs or changes needed you notice from now on.

Unfortunately, I haven't write any tests over all this time (what a shame). If I had, we could just run the tests and see what needs to be fixed. Now sadly this has to be done by checking each functionality manually by hand. 

Regarding the complete re-write I was thinking of (MVC-like code organization and tests!!!) unfortunately I will have to delay it for even longer. So, the plan for now is to complete the port to pyqt5, implement some of the feature requests and some other small features/changes I have on mind and release a version.

Feel free to contribute with any way you wish!

Cheers!

**Comment by Ilias95** [comment]
I think that the port is complete. I merged the pyqt5 branch to the master. Now some extensive testing has to be done. 

I'll also start implementing some new stuff.
