### ISSUE TITLE
Getting "ImportError" on Ubuntu 16.04

### ISSUE THREAD

**Issue by Backolous** [Ilias95/FF-Multi-Converter#48]
Hi,
i installed ffmulticonverter using this Tutorial: https://github.com/Ilias95/FF-Multi-Converter/wiki/Installing-from-source .
Now I get the following Errors when i try to start the program:
`Traceback (most recent call last):
  File "/usr/local/bin/ffmulticonverter", line 4, in <module>
    from ffmulticonverter import ffmulticonverter
  File "/usr/local/lib/python3.5/dist-packages/ffmulticonverter/ffmulticonverter.py", line 20, in <module>
    from __init__ import __version__
ImportError: No module named '__init__'`

Can you please help me to solve the Problem?

**Comment by Ilias95** [comment]
Hello,

Please tell me the following:
1. What is your distribution.
2. What version of the app did you install.
3. How did you try to run it?

**Comment by Backolous** [comment]
Hi,
1.I am using an fresh installed Version of Ubuntu 16.04 64-bit. 
2.This one: https://github.com/downloads/Ilias95/FF-Multi-Converter/ffmulticonverter-1.4.3.tar.gz
3. I installed with the Script and then tried to lauch in Terminal ffmulticonverter.

**Comment by Ilias95** [comment]
Oh, your distro was stated on the title, sorry for missing that. 

Why don't you try to install the latest 1.7.2 version from sourceforge? Just run the unistall.sh you will find in the 1.7.2 package prior to the installation and then follow the exact same procedure as you did.

Also please tell me what "python -V" returns on ubuntu 16.04.

**Comment by Backolous** [comment]
Now it works, thank you! I didn't notice that there is a newer Version on sourceforge...
`python -V
Python 2.7.11+
`
