### ISSUE TITLE
Incorrect desktop-file

### ISSUE THREAD

**Issue by Vascom** [Ilias95/FF-Multi-Converter#51]
Please correct this warnings:

ffmulticonverter.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
ffmulticonverter.desktop: warning: value "Application;AudioVideo;AudioVideoEditing;Office;" for key "Categories" in group "Desktop Entry" contains a deprecated value "Application"
ffmulticonverter.desktop: hint: value "Application;AudioVideo;AudioVideoEditing;Office;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu

**Comment by Ilias95** [comment]
Hi, I apologize for forgetting this one.
Done: 215aa3cfe6263c456ac062e561955e42cbad7e39
Thanks.
