### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by wildbuttrueblue** [Ilias95/FF-Multi-Converter#55]
$ ffmulticonverter
Traceback (most recent call last):
  File "/usr/local/bin/ffmulticonverter", line 4, in <module>
    from ffmulticonverter import ffmulticonverter
  File "/usr/local/lib/python3.5/dist-packages/ffmulticonverter/ffmulticonverter.py", line 23, in <module>
    from PyQt5.QtGui import QIcon, QKeySequence
ImportError: No module named 'PyQt5'

**Comment by Ilias95** [comment]
Hello.
Clearly you don't have PyQt5 for python3 installed.
How did you install the app and in which distribution?

**Comment by wildbuttrueblue** [comment]
From Source Forge https://sourceforge.net/projects/ffmulticonv/?source=typ_redirect

[sudo] password for kevin: 
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
copying build/scripts-3.5/ffmulticonverter -> /usr/local/bin
changing mode of /usr/local/bin/ffmulticonverter to 775
running install_data
running install_egg_info
Removing /usr/local/lib/python3.5/dist-packages/ffmulticonverter-1.8.0.egg-info
Writing /usr/local/lib/python3.5/dist-packages/ffmulticonverter-1.8.0.egg-info
kevin@WBC-Ubuntu:~/ffconver/ffmulticonverter-1.8.0$ dir
AUTHORS  ChangeLog	   launcher  PKG-INFO	    setup.py  TRANSLATORS
bin	 COPYING	   locale    README.txt     share     uninstall.sh
build	 ffmulticonverter  man	     resources.qrc  test
kevin@WBC-Ubuntu:~/ffconver/ffmulticonverter-1.8.0$ ffmulticonverter
Traceback (most recent call last):
  File "/usr/local/bin/ffmulticonverter", line 4, in <module>
    from ffmulticonverter import ffmulticonverter
  File "/usr/local/lib/python3.5/dist-packages/ffmulticonverter/ffmulticonverter.py", line 23, in <module>
    from PyQt5.QtGui import QIcon, QKeySequence
ImportError: No module named 'PyQt5'

**Comment by wildbuttrueblue** [comment]
Attempting to install kevin@WBC-Ubuntu:~$ pip3 install pyqt5
per instructions from http://pyqt.sourceforge.net/Docs/PyQt5/installation.html

**Comment by Ilias95** [comment]
You can install the python3-pyqt5 packet from the Software Center in Ubuntu.

**Comment by wildbuttrueblue** [comment]
thank you llias95 am attempting the aforementioned command at the moment, if that does not work will attempt from the Software Center.

Is there a way to determine if pyqt5 is installed on the system?

**Comment by wildbuttrueblue** [comment]
kevin@WBC-Ubuntu:~$ pip3 install pyqt5
Collecting pyqt5
  Downloading PyQt5-5.7-cp35-cp35m-manylinux1_x86_64.whl (89.8MB)
    100% |████████████████████████████████| 89.8MB 7.7kB/s 
Collecting sip (from pyqt5)
  Downloading sip-4.18.1-cp35-cp35m-manylinux1_x86_64.whl (60kB)
    100% |████████████████████████████████| 61kB 104kB/s 
Installing collected packages: sip, pyqt5
Successfully installed pyqt5 sip
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by wildbuttrueblue** [comment]
successfully ran ffmulticonverter.  Testing it out now.

**Comment by Ilias95** [comment]
It is much better to install it with the package manager of your distribution (in this case through Software Center) for a lot of reasons. I strongly suggest you to do it this way. It's clearly not installed, that what you get this specific error message. You can also verify that by searching the package in Software Center / synaptic or running the appropriate command on a terminal.

**Comment by wildbuttrueblue** [comment]
Thank you llias95, as it seems to be working correctly now, after installing via the command above, is there any reason or need to install it through the Software Center?

**Comment by Ilias95** [comment]
Everything installed from your package manager is updated "automatically" from your package manager along with all the other applications installed on your system. Now, in order to receive updates for this specific package, you have to do it using pip (another package manager for python software). Also your package manager deals with dependencies of other packages and stuff. You should always install something from your distribution's official package manager if there is this option.

**Comment by wildbuttrueblue** [comment]
Thank you llias95, will remember that!  Good advice - will close this now and thank you for all your input and assistance!  

~Regards

**Comment by Ilias95** [comment]
You're welcome! :)
