### ISSUE TITLE
compilation failed on my Debian box

### ISSUE THREAD

**Issue by OrionRandD** [Ilias95/FF-Multi-Converter#56]
I have installed all the dependencies:
apt install python3 python3-pyqt4 python3-pyqt5 unoconv python
-magic ffmpeg   
Upon running "./setup.py install"  the program installs without any error, but when I call it I get this error:

ffmulticonverter 
Traceback (most recent call last):
  File "/usr/local/bin/ffmulticonverter", line 4, in <module>
    from ffmulticonverter import ffmulticonverter
  File "/usr/local/lib/python3.5/dist-packages/ffmulticonverter/ffmulticonverter.py", line 20, in <module>
    from __init__ import __version__
ImportError: No module named '__init__'

:(

**Comment by Ilias95** [comment]
Hello. 
Which version are you trying to install and where did you get it from?

**Comment by OrionRandD** [comment]
Hi,
Thx for the prompt reply.
I have found out that I was using an much more older version 1.4
and I found out a new one here:
https://sourceforge.net/projects/ffmulticonv/?source=typ_redirect

I've installed it and now everything is alright...
Thx a lot...

**Comment by OrionRandD** [comment]
On Thu, 23 Mar 2017, Ilias Stamatis wrote:

> 
> Hello.
> Which version are you trying to install and where did you get it from?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[ARYrdW75YT2YDYWTlLdylUDJWY81RIKGks5roteegaJpZM4MnUuP.gif]
> 
> 
>

Hi,
Thx for the prompt reply.
I have found out that I was using an much more older version 1.4
and I found out a new one here:
https://sourceforge.net/projects/ffmulticonv/?source=typ_redirect

I've installed it and now everything is alright...
Thx a lot...

-- 
https://wire.com/en/
https://app.wire.com/auth/#login

Find me in
Encontre-me em
@odysseus
vagnerrener@gmail.com
